### PR TITLE
Add codeowner file

### PR DESCRIPTION
**Pull request by nk-ty**

### CODE REVIEW

**Review by hikimochi — APPROVED** [review]
LGTM

**Comment by hikimochi** [comment]
@nk-ty
How about increasing approvals? 1 -> 2

**Comment by nk-ty** [comment]
@hikimochi 
> @nk-ty How about increasing approvals? 1 -> 2
Could you tell me the purpose?

**Comment by hikimochi** [comment]
@nk-ty 
It will be safer than alone. 😋

**Comment by nk-ty** [comment]
Right. Updated branch setting!
Thanks for your suggestion.

**Pull request merged**
